// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/environment.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationType int32

const (
	OperationType_DEPLOY OperationType = 0
	OperationType_DELETE OperationType = 1
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "DEPLOY",
		1: "DELETE",
	}
	OperationType_value = map[string]int32{
		"DEPLOY": 0,
		"DELETE": 1,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_environment_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_proto_environment_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{0}
}

// RegisterRequest is sent by the environment agent on startup.
type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentName string                 `protobuf:"bytes,1,opt,name=environment_name,json=environmentName,proto3" json:"environment_name,omitempty"`
	Config          *EnvironmentConfig     `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Recipes         []*RecipeRegistration  `protobuf:"bytes,3,rep,name=recipes,proto3" json:"recipes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_environment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEnvironmentName() string {
	if x != nil {
		return x.EnvironmentName
	}
	return ""
}

func (x *RegisterRequest) GetConfig() *EnvironmentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RegisterRequest) GetRecipes() []*RecipeRegistration {
	if x != nil {
		return x.Recipes
	}
	return nil
}

type EnvironmentConfig struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	Providers          map[string]*ProviderConfig `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TerraformProviders map[string]string          `protobuf:"bytes,2,rep,name=terraform_providers,json=terraformProviders,proto3" json:"terraform_providers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // provider name -> JSON config
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EnvironmentConfig) Reset() {
	*x = EnvironmentConfig{}
	mi := &file_proto_environment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentConfig) ProtoMessage() {}

func (x *EnvironmentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentConfig.ProtoReflect.Descriptor instead.
func (*EnvironmentConfig) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{1}
}

func (x *EnvironmentConfig) GetProviders() map[string]*ProviderConfig {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *EnvironmentConfig) GetTerraformProviders() map[string]string {
	if x != nil {
		return x.TerraformProviders
	}
	return nil
}

type ProviderConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderConfig) Reset() {
	*x = ProviderConfig{}
	mi := &file_proto_environment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConfig) ProtoMessage() {}

func (x *ProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConfig.ProtoReflect.Descriptor instead.
func (*ProviderConfig) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderConfig) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type RecipeRegistration struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ResourceType      string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // e.g. "Ryobi.Compute/containers"
	RecipeName        string                 `protobuf:"bytes,2,opt,name=recipe_name,json=recipeName,proto3" json:"recipe_name,omitempty"`       // e.g. "kubernetes"
	TemplatePath      string                 `protobuf:"bytes,3,opt,name=template_path,json=templatePath,proto3" json:"template_path,omitempty"` // absolute path to terraform module
	DefaultParameters map[string]string      `protobuf:"bytes,4,rep,name=default_parameters,json=defaultParameters,proto3" json:"default_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecipeRegistration) Reset() {
	*x = RecipeRegistration{}
	mi := &file_proto_environment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeRegistration) ProtoMessage() {}

func (x *RecipeRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeRegistration.ProtoReflect.Descriptor instead.
func (*RecipeRegistration) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{3}
}

func (x *RecipeRegistration) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *RecipeRegistration) GetRecipeName() string {
	if x != nil {
		return x.RecipeName
	}
	return ""
}

func (x *RecipeRegistration) GetTemplatePath() string {
	if x != nil {
		return x.TemplatePath
	}
	return ""
}

func (x *RecipeRegistration) GetDefaultParameters() map[string]string {
	if x != nil {
		return x.DefaultParameters
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,3,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_environment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

type UnregisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentName string                 `protobuf:"bytes,1,opt,name=environment_name,json=environmentName,proto3" json:"environment_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_proto_environment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterRequest) GetEnvironmentName() string {
	if x != nil {
		return x.EnvironmentName
	}
	return ""
}

type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_proto_environment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{6}
}

func (x *UnregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// WatchRequest initiates a watch stream for a specific environment.
type WatchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentName string                 `protobuf:"bytes,1,opt,name=environment_name,json=environmentName,proto3" json:"environment_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_environment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{7}
}

func (x *WatchRequest) GetEnvironmentName() string {
	if x != nil {
		return x.EnvironmentName
	}
	return ""
}

// ResourceEvent is pushed from the server to the environment agent.
type ResourceEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OperationId     string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ResourceId      string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceName    string                 `protobuf:"bytes,3,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ResourceType    string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	RecipeName      string                 `protobuf:"bytes,5,opt,name=recipe_name,json=recipeName,proto3" json:"recipe_name,omitempty"`
	Operation       OperationType          `protobuf:"varint,6,opt,name=operation,proto3,enum=ryobi.environment.v1.OperationType" json:"operation,omitempty"`
	Parameters      map[string]string      `protobuf:"bytes,7,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ApplicationName string                 `protobuf:"bytes,8,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceEvent) Reset() {
	*x = ResourceEvent{}
	mi := &file_proto_environment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceEvent) ProtoMessage() {}

func (x *ResourceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceEvent.ProtoReflect.Descriptor instead.
func (*ResourceEvent) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{8}
}

func (x *ResourceEvent) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ResourceEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ResourceEvent) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *ResourceEvent) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ResourceEvent) GetRecipeName() string {
	if x != nil {
		return x.RecipeName
	}
	return ""
}

func (x *ResourceEvent) GetOperation() OperationType {
	if x != nil {
		return x.Operation
	}
	return OperationType_DEPLOY
}

func (x *ResourceEvent) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ResourceEvent) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

// ReportResultRequest is sent by the environment agent after processing.
type ReportResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Outputs       map[string]string      `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_proto_environment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{9}
}

func (x *ReportResultRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ReportResultRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ReportResultRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportResultRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReportResultRequest) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_proto_environment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{10}
}

func (x *ReportResultResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_proto_environment_proto protoreflect.FileDescriptor

const file_proto_environment_proto_rawDesc = "" +
	"\n" +
	"\x17proto/environment.proto\x12\x14ryobi.environment.v1\"\xc1\x01\n" +
	"\x0fRegisterRequest\x12)\n" +
	"\x10environment_name\x18\x01 \x01(\tR\x0fenvironmentName\x12?\n" +
	"\x06config\x18\x02 \x01(\v2'.ryobi.environment.v1.EnvironmentConfigR\x06config\x12B\n" +
	"\arecipes\x18\x03 \x03(\v2(.ryobi.environment.v1.RecipeRegistrationR\arecipes\"\x86\x03\n" +
	"\x11EnvironmentConfig\x12T\n" +
	"\tproviders\x18\x01 \x03(\v26.ryobi.environment.v1.EnvironmentConfig.ProvidersEntryR\tproviders\x12p\n" +
	"\x13terraform_providers\x18\x02 \x03(\v2?.ryobi.environment.v1.EnvironmentConfig.TerraformProvidersEntryR\x12terraformProviders\x1ab\n" +
	"\x0eProvidersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.ryobi.environment.v1.ProviderConfigR\x05value:\x028\x01\x1aE\n" +
	"\x17TerraformProvidersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\x0eProviderConfig\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\"\xb5\x02\n" +
	"\x12RecipeRegistration\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vrecipe_name\x18\x02 \x01(\tR\n" +
	"recipeName\x12#\n" +
	"\rtemplate_path\x18\x03 \x01(\tR\ftemplatePath\x12n\n" +
	"\x12default_parameters\x18\x04 \x03(\v2?.ryobi.environment.v1.RecipeRegistration.DefaultParametersEntryR\x11defaultParameters\x1aD\n" +
	"\x16DefaultParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eenvironment_id\x18\x03 \x01(\tR\renvironmentId\">\n" +
	"\x11UnregisterRequest\x12)\n" +
	"\x10environment_name\x18\x01 \x01(\tR\x0fenvironmentName\".\n" +
	"\x12UnregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"9\n" +
	"\fWatchRequest\x12)\n" +
	"\x10environment_name\x18\x01 \x01(\tR\x0fenvironmentName\"\xc0\x03\n" +
	"\rResourceEvent\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_name\x18\x03 \x01(\tR\fresourceName\x12#\n" +
	"\rresource_type\x18\x04 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vrecipe_name\x18\x05 \x01(\tR\n" +
	"recipeName\x12A\n" +
	"\toperation\x18\x06 \x01(\x0e2#.ryobi.environment.v1.OperationTypeR\toperation\x12S\n" +
	"\n" +
	"parameters\x18\a \x03(\v23.ryobi.environment.v1.ResourceEvent.ParametersEntryR\n" +
	"parameters\x12)\n" +
	"\x10application_name\x18\b \x01(\tR\x0fapplicationName\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x02\n" +
	"\x13ReportResultRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12P\n" +
	"\aoutputs\x18\x05 \x03(\v26.ryobi.environment.v1.ReportResultRequest.OutputsEntryR\aoutputs\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x14ReportResultResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged*'\n" +
	"\rOperationType\x12\n" +
	"\n" +
	"\x06DEPLOY\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x012\x94\x03\n" +
	"\x12EnvironmentService\x12Y\n" +
	"\bRegister\x12%.ryobi.environment.v1.RegisterRequest\x1a&.ryobi.environment.v1.RegisterResponse\x12_\n" +
	"\n" +
	"Unregister\x12'.ryobi.environment.v1.UnregisterRequest\x1a(.ryobi.environment.v1.UnregisterResponse\x12[\n" +
	"\x0eWatchResources\x12\".ryobi.environment.v1.WatchRequest\x1a#.ryobi.environment.v1.ResourceEvent0\x01\x12e\n" +
	"\fReportResult\x12).ryobi.environment.v1.ReportResultRequest\x1a*.ryobi.environment.v1.ReportResultResponseB,Z*github.com/ryobi-project/ryobi/pkg/grpcapib\x06proto3"

var (
	file_proto_environment_proto_rawDescOnce sync.Once
	file_proto_environment_proto_rawDescData []byte
)

func file_proto_environment_proto_rawDescGZIP() []byte {
	file_proto_environment_proto_rawDescOnce.Do(func() {
		file_proto_environment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_environment_proto_rawDesc), len(file_proto_environment_proto_rawDesc)))
	})
	return file_proto_environment_proto_rawDescData
}

var file_proto_environment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_environment_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_environment_proto_goTypes = []any{
	(OperationType)(0),           // 0: ryobi.environment.v1.OperationType
	(*RegisterRequest)(nil),      // 1: ryobi.environment.v1.RegisterRequest
	(*EnvironmentConfig)(nil),    // 2: ryobi.environment.v1.EnvironmentConfig
	(*ProviderConfig)(nil),       // 3: ryobi.environment.v1.ProviderConfig
	(*RecipeRegistration)(nil),   // 4: ryobi.environment.v1.RecipeRegistration
	(*RegisterResponse)(nil),     // 5: ryobi.environment.v1.RegisterResponse
	(*UnregisterRequest)(nil),    // 6: ryobi.environment.v1.UnregisterRequest
	(*UnregisterResponse)(nil),   // 7: ryobi.environment.v1.UnregisterResponse
	(*WatchRequest)(nil),         // 8: ryobi.environment.v1.WatchRequest
	(*ResourceEvent)(nil),        // 9: ryobi.environment.v1.ResourceEvent
	(*ReportResultRequest)(nil),  // 10: ryobi.environment.v1.ReportResultRequest
	(*ReportResultResponse)(nil), // 11: ryobi.environment.v1.ReportResultResponse
	nil,                          // 12: ryobi.environment.v1.EnvironmentConfig.ProvidersEntry
	nil,                          // 13: ryobi.environment.v1.EnvironmentConfig.TerraformProvidersEntry
	nil,                          // 14: ryobi.environment.v1.RecipeRegistration.DefaultParametersEntry
	nil,                          // 15: ryobi.environment.v1.ResourceEvent.ParametersEntry
	nil,                          // 16: ryobi.environment.v1.ReportResultRequest.OutputsEntry
}
var file_proto_environment_proto_depIdxs = []int32{
	2,  // 0: ryobi.environment.v1.RegisterRequest.config:type_name -> ryobi.environment.v1.EnvironmentConfig
	4,  // 1: ryobi.environment.v1.RegisterRequest.recipes:type_name -> ryobi.environment.v1.RecipeRegistration
	12, // 2: ryobi.environment.v1.EnvironmentConfig.providers:type_name -> ryobi.environment.v1.EnvironmentConfig.ProvidersEntry
	13, // 3: ryobi.environment.v1.EnvironmentConfig.terraform_providers:type_name -> ryobi.environment.v1.EnvironmentConfig.TerraformProvidersEntry
	14, // 4: ryobi.environment.v1.RecipeRegistration.default_parameters:type_name -> ryobi.environment.v1.RecipeRegistration.DefaultParametersEntry
	0,  // 5: ryobi.environment.v1.ResourceEvent.operation:type_name -> ryobi.environment.v1.OperationType
	15, // 6: ryobi.environment.v1.ResourceEvent.parameters:type_name -> ryobi.environment.v1.ResourceEvent.ParametersEntry
	16, // 7: ryobi.environment.v1.ReportResultRequest.outputs:type_name -> ryobi.environment.v1.ReportResultRequest.OutputsEntry
	3,  // 8: ryobi.environment.v1.EnvironmentConfig.ProvidersEntry.value:type_name -> ryobi.environment.v1.ProviderConfig
	1,  // 9: ryobi.environment.v1.EnvironmentService.Register:input_type -> ryobi.environment.v1.RegisterRequest
	6,  // 10: ryobi.environment.v1.EnvironmentService.Unregister:input_type -> ryobi.environment.v1.UnregisterRequest
	8,  // 11: ryobi.environment.v1.EnvironmentService.WatchResources:input_type -> ryobi.environment.v1.WatchRequest
	10, // 12: ryobi.environment.v1.EnvironmentService.ReportResult:input_type -> ryobi.environment.v1.ReportResultRequest
	5,  // 13: ryobi.environment.v1.EnvironmentService.Register:output_type -> ryobi.environment.v1.RegisterResponse
	7,  // 14: ryobi.environment.v1.EnvironmentService.Unregister:output_type -> ryobi.environment.v1.UnregisterResponse
	9,  // 15: ryobi.environment.v1.EnvironmentService.WatchResources:output_type -> ryobi.environment.v1.ResourceEvent
	11, // 16: ryobi.environment.v1.EnvironmentService.ReportResult:output_type -> ryobi.environment.v1.ReportResultResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_environment_proto_init() }
func file_proto_environment_proto_init() {
	if File_proto_environment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_environment_proto_rawDesc), len(file_proto_environment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_environment_proto_goTypes,
		DependencyIndexes: file_proto_environment_proto_depIdxs,
		EnumInfos:         file_proto_environment_proto_enumTypes,
		MessageInfos:      file_proto_environment_proto_msgTypes,
	}.Build()
	File_proto_environment_proto = out.File
	file_proto_environment_proto_goTypes = nil
	file_proto_environment_proto_depIdxs = nil
}
