// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/environment.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationType int32

const (
	OperationType_DEPLOY OperationType = 0
	OperationType_DELETE OperationType = 1
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "DEPLOY",
		1: "DELETE",
	}
	OperationType_value = map[string]int32{
		"DEPLOY": 0,
		"DELETE": 1,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_environment_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_proto_environment_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	EnvironmentName string                   `protobuf:"bytes,1,opt,name=environment_name,json=environmentName,proto3" json:"environment_name,omitempty"`
	Config          *EnvironmentConfig       `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Recipes         []*RecipeRegistration    `protobuf:"bytes,3,rep,name=recipes,proto3" json:"recipes,omitempty"`
	Capabilities    *EnvironmentCapabilities `protobuf:"bytes,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_environment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEnvironmentName() string {
	if x != nil {
		return x.EnvironmentName
	}
	return ""
}

func (x *RegisterRequest) GetConfig() *EnvironmentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RegisterRequest) GetRecipes() []*RecipeRegistration {
	if x != nil {
		return x.Recipes
	}
	return nil
}

func (x *RegisterRequest) GetCapabilities() *EnvironmentCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type EnvironmentConfig struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	Providers          map[string]*ProviderConfig `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TerraformProviders map[string]string          `protobuf:"bytes,2,rep,name=terraform_providers,json=terraformProviders,proto3" json:"terraform_providers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EnvironmentConfig) Reset() {
	*x = EnvironmentConfig{}
	mi := &file_proto_environment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentConfig) ProtoMessage() {}

func (x *EnvironmentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentConfig.ProtoReflect.Descriptor instead.
func (*EnvironmentConfig) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{1}
}

func (x *EnvironmentConfig) GetProviders() map[string]*ProviderConfig {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *EnvironmentConfig) GetTerraformProviders() map[string]string {
	if x != nil {
		return x.TerraformProviders
	}
	return nil
}

type ProviderConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderConfig) Reset() {
	*x = ProviderConfig{}
	mi := &file_proto_environment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConfig) ProtoMessage() {}

func (x *ProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConfig.ProtoReflect.Descriptor instead.
func (*ProviderConfig) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderConfig) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type RecipeRegistration struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ResourceType      string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	RecipeName        string                 `protobuf:"bytes,2,opt,name=recipe_name,json=recipeName,proto3" json:"recipe_name,omitempty"`
	TemplatePath      string                 `protobuf:"bytes,3,opt,name=template_path,json=templatePath,proto3" json:"template_path,omitempty"`
	DefaultParameters map[string]string      `protobuf:"bytes,4,rep,name=default_parameters,json=defaultParameters,proto3" json:"default_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecipeRegistration) Reset() {
	*x = RecipeRegistration{}
	mi := &file_proto_environment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeRegistration) ProtoMessage() {}

func (x *RecipeRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeRegistration.ProtoReflect.Descriptor instead.
func (*RecipeRegistration) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{3}
}

func (x *RecipeRegistration) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *RecipeRegistration) GetRecipeName() string {
	if x != nil {
		return x.RecipeName
	}
	return ""
}

func (x *RecipeRegistration) GetTemplatePath() string {
	if x != nil {
		return x.TemplatePath
	}
	return ""
}

func (x *RecipeRegistration) GetDefaultParameters() map[string]string {
	if x != nil {
		return x.DefaultParameters
	}
	return nil
}

// EnvironmentCapabilities describes what an environment can do.
// Static capabilities are set in config and sent at registration.
type EnvironmentCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Sovereignty   string                 `protobuf:"bytes,2,opt,name=sovereignty,proto3" json:"sovereignty,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // e.g. ["gpu", "high-memory"]
	CostPerHour   float64                `protobuf:"fixed64,4,opt,name=cost_per_hour,json=costPerHour,proto3" json:"cost_per_hour,omitempty"`
	MaxReplicas   int32                  `protobuf:"varint,5,opt,name=max_replicas,json=maxReplicas,proto3" json:"max_replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentCapabilities) Reset() {
	*x = EnvironmentCapabilities{}
	mi := &file_proto_environment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentCapabilities) ProtoMessage() {}

func (x *EnvironmentCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentCapabilities.ProtoReflect.Descriptor instead.
func (*EnvironmentCapabilities) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{4}
}

func (x *EnvironmentCapabilities) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *EnvironmentCapabilities) GetSovereignty() string {
	if x != nil {
		return x.Sovereignty
	}
	return ""
}

func (x *EnvironmentCapabilities) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *EnvironmentCapabilities) GetCostPerHour() float64 {
	if x != nil {
		return x.CostPerHour
	}
	return 0
}

func (x *EnvironmentCapabilities) GetMaxReplicas() int32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,3,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_environment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

type UnregisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentName string                 `protobuf:"bytes,1,opt,name=environment_name,json=environmentName,proto3" json:"environment_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_proto_environment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{6}
}

func (x *UnregisterRequest) GetEnvironmentName() string {
	if x != nil {
		return x.EnvironmentName
	}
	return ""
}

type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_proto_environment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{7}
}

func (x *UnregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WatchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentName string                 `protobuf:"bytes,1,opt,name=environment_name,json=environmentName,proto3" json:"environment_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_environment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{8}
}

func (x *WatchRequest) GetEnvironmentName() string {
	if x != nil {
		return x.EnvironmentName
	}
	return ""
}

type ResourceEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OperationId     string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ResourceId      string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceName    string                 `protobuf:"bytes,3,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ResourceType    string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	RecipeName      string                 `protobuf:"bytes,5,opt,name=recipe_name,json=recipeName,proto3" json:"recipe_name,omitempty"`
	Operation       OperationType          `protobuf:"varint,6,opt,name=operation,proto3,enum=ryobi.environment.v1.OperationType" json:"operation,omitempty"`
	Parameters      map[string]string      `protobuf:"bytes,7,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ApplicationName string                 `protobuf:"bytes,8,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceEvent) Reset() {
	*x = ResourceEvent{}
	mi := &file_proto_environment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceEvent) ProtoMessage() {}

func (x *ResourceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceEvent.ProtoReflect.Descriptor instead.
func (*ResourceEvent) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{9}
}

func (x *ResourceEvent) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ResourceEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ResourceEvent) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *ResourceEvent) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ResourceEvent) GetRecipeName() string {
	if x != nil {
		return x.RecipeName
	}
	return ""
}

func (x *ResourceEvent) GetOperation() OperationType {
	if x != nil {
		return x.Operation
	}
	return OperationType_DEPLOY
}

func (x *ResourceEvent) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ResourceEvent) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

type ReportResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Outputs       map[string]string      `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_proto_environment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{10}
}

func (x *ReportResultRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ReportResultRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ReportResultRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportResultRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReportResultRequest) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_proto_environment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{11}
}

func (x *ReportResultResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type ReportStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceName  string                 `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Health        *ResourceHealthStatus  `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusRequest) Reset() {
	*x = ReportStatusRequest{}
	mi := &file_proto_environment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusRequest) ProtoMessage() {}

func (x *ReportStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{12}
}

func (x *ReportStatusRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ReportStatusRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *ReportStatusRequest) GetHealth() *ResourceHealthStatus {
	if x != nil {
		return x.Health
	}
	return nil
}

type ResourceHealthStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	State           string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`                                                                                     // "Running", "Degraded", "Down", "Unknown"
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                                 // human-readable description
	ReadyReplicas   int32                  `protobuf:"varint,3,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`                                               // for deployments: ready pods
	DesiredReplicas int32                  `protobuf:"varint,4,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`                                         // for deployments: desired pods
	LastUpdated     int64                  `protobuf:"varint,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`                                                     // unix timestamp
	Properties      map[string]string      `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // provider-specific info
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceHealthStatus) Reset() {
	*x = ResourceHealthStatus{}
	mi := &file_proto_environment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceHealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceHealthStatus) ProtoMessage() {}

func (x *ResourceHealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceHealthStatus.ProtoReflect.Descriptor instead.
func (*ResourceHealthStatus) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{13}
}

func (x *ResourceHealthStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ResourceHealthStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResourceHealthStatus) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *ResourceHealthStatus) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *ResourceHealthStatus) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *ResourceHealthStatus) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type ReportStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusResponse) Reset() {
	*x = ReportStatusResponse{}
	mi := &file_proto_environment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusResponse) ProtoMessage() {}

func (x *ReportStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{14}
}

func (x *ReportStatusResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type HeartbeatRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentName        string                 `protobuf:"bytes,1,opt,name=environment_name,json=environmentName,proto3" json:"environment_name,omitempty"`
	AvailableCpuMillicores int64                  `protobuf:"varint,2,opt,name=available_cpu_millicores,json=availableCpuMillicores,proto3" json:"available_cpu_millicores,omitempty"`
	AvailableMemoryMb      int64                  `protobuf:"varint,3,opt,name=available_memory_mb,json=availableMemoryMb,proto3" json:"available_memory_mb,omitempty"`
	RunningResources       int32                  `protobuf:"varint,4,opt,name=running_resources,json=runningResources,proto3" json:"running_resources,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_environment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{15}
}

func (x *HeartbeatRequest) GetEnvironmentName() string {
	if x != nil {
		return x.EnvironmentName
	}
	return ""
}

func (x *HeartbeatRequest) GetAvailableCpuMillicores() int64 {
	if x != nil {
		return x.AvailableCpuMillicores
	}
	return 0
}

func (x *HeartbeatRequest) GetAvailableMemoryMb() int64 {
	if x != nil {
		return x.AvailableMemoryMb
	}
	return 0
}

func (x *HeartbeatRequest) GetRunningResources() int32 {
	if x != nil {
		return x.RunningResources
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_environment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_environment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_environment_proto_rawDescGZIP(), []int{16}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_proto_environment_proto protoreflect.FileDescriptor

const file_proto_environment_proto_rawDesc = "" +
	"\n" +
	"\x17proto/environment.proto\x12\x14ryobi.environment.v1\"\x94\x02\n" +
	"\x0fRegisterRequest\x12)\n" +
	"\x10environment_name\x18\x01 \x01(\tR\x0fenvironmentName\x12?\n" +
	"\x06config\x18\x02 \x01(\v2'.ryobi.environment.v1.EnvironmentConfigR\x06config\x12B\n" +
	"\arecipes\x18\x03 \x03(\v2(.ryobi.environment.v1.RecipeRegistrationR\arecipes\x12Q\n" +
	"\fcapabilities\x18\x04 \x01(\v2-.ryobi.environment.v1.EnvironmentCapabilitiesR\fcapabilities\"\x86\x03\n" +
	"\x11EnvironmentConfig\x12T\n" +
	"\tproviders\x18\x01 \x03(\v26.ryobi.environment.v1.EnvironmentConfig.ProvidersEntryR\tproviders\x12p\n" +
	"\x13terraform_providers\x18\x02 \x03(\v2?.ryobi.environment.v1.EnvironmentConfig.TerraformProvidersEntryR\x12terraformProviders\x1ab\n" +
	"\x0eProvidersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.ryobi.environment.v1.ProviderConfigR\x05value:\x028\x01\x1aE\n" +
	"\x17TerraformProvidersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\x0eProviderConfig\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\"\xb5\x02\n" +
	"\x12RecipeRegistration\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vrecipe_name\x18\x02 \x01(\tR\n" +
	"recipeName\x12#\n" +
	"\rtemplate_path\x18\x03 \x01(\tR\ftemplatePath\x12n\n" +
	"\x12default_parameters\x18\x04 \x03(\v2?.ryobi.environment.v1.RecipeRegistration.DefaultParametersEntryR\x11defaultParameters\x1aD\n" +
	"\x16DefaultParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbe\x01\n" +
	"\x17EnvironmentCapabilities\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12 \n" +
	"\vsovereignty\x18\x02 \x01(\tR\vsovereignty\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12\"\n" +
	"\rcost_per_hour\x18\x04 \x01(\x01R\vcostPerHour\x12!\n" +
	"\fmax_replicas\x18\x05 \x01(\x05R\vmaxReplicas\"m\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eenvironment_id\x18\x03 \x01(\tR\renvironmentId\">\n" +
	"\x11UnregisterRequest\x12)\n" +
	"\x10environment_name\x18\x01 \x01(\tR\x0fenvironmentName\".\n" +
	"\x12UnregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"9\n" +
	"\fWatchRequest\x12)\n" +
	"\x10environment_name\x18\x01 \x01(\tR\x0fenvironmentName\"\xc0\x03\n" +
	"\rResourceEvent\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_name\x18\x03 \x01(\tR\fresourceName\x12#\n" +
	"\rresource_type\x18\x04 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vrecipe_name\x18\x05 \x01(\tR\n" +
	"recipeName\x12A\n" +
	"\toperation\x18\x06 \x01(\x0e2#.ryobi.environment.v1.OperationTypeR\toperation\x12S\n" +
	"\n" +
	"parameters\x18\a \x03(\v23.ryobi.environment.v1.ResourceEvent.ParametersEntryR\n" +
	"parameters\x12)\n" +
	"\x10application_name\x18\b \x01(\tR\x0fapplicationName\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x02\n" +
	"\x13ReportResultRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12P\n" +
	"\aoutputs\x18\x05 \x03(\v26.ryobi.environment.v1.ReportResultRequest.OutputsEntryR\aoutputs\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x14ReportResultResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\x9f\x01\n" +
	"\x13ReportStatusRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_name\x18\x02 \x01(\tR\fresourceName\x12B\n" +
	"\x06health\x18\x03 \x01(\v2*.ryobi.environment.v1.ResourceHealthStatusR\x06health\"\xd6\x02\n" +
	"\x14ResourceHealthStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eready_replicas\x18\x03 \x01(\x05R\rreadyReplicas\x12)\n" +
	"\x10desired_replicas\x18\x04 \x01(\x05R\x0fdesiredReplicas\x12!\n" +
	"\flast_updated\x18\x05 \x01(\x03R\vlastUpdated\x12Z\n" +
	"\n" +
	"properties\x18\x06 \x03(\v2:.ryobi.environment.v1.ResourceHealthStatus.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x14ReportStatusResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\xd4\x01\n" +
	"\x10HeartbeatRequest\x12)\n" +
	"\x10environment_name\x18\x01 \x01(\tR\x0fenvironmentName\x128\n" +
	"\x18available_cpu_millicores\x18\x02 \x01(\x03R\x16availableCpuMillicores\x12.\n" +
	"\x13available_memory_mb\x18\x03 \x01(\x03R\x11availableMemoryMb\x12+\n" +
	"\x11running_resources\x18\x04 \x01(\x05R\x10runningResources\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged*'\n" +
	"\rOperationType\x12\n" +
	"\n" +
	"\x06DEPLOY\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x012\xd9\x04\n" +
	"\x12EnvironmentService\x12Y\n" +
	"\bRegister\x12%.ryobi.environment.v1.RegisterRequest\x1a&.ryobi.environment.v1.RegisterResponse\x12_\n" +
	"\n" +
	"Unregister\x12'.ryobi.environment.v1.UnregisterRequest\x1a(.ryobi.environment.v1.UnregisterResponse\x12[\n" +
	"\x0eWatchResources\x12\".ryobi.environment.v1.WatchRequest\x1a#.ryobi.environment.v1.ResourceEvent0\x01\x12e\n" +
	"\fReportResult\x12).ryobi.environment.v1.ReportResultRequest\x1a*.ryobi.environment.v1.ReportResultResponse\x12e\n" +
	"\fReportStatus\x12).ryobi.environment.v1.ReportStatusRequest\x1a*.ryobi.environment.v1.ReportStatusResponse\x12\\\n" +
	"\tHeartbeat\x12&.ryobi.environment.v1.HeartbeatRequest\x1a'.ryobi.environment.v1.HeartbeatResponseB,Z*github.com/ryobi-project/ryobi/pkg/grpcapib\x06proto3"

var (
	file_proto_environment_proto_rawDescOnce sync.Once
	file_proto_environment_proto_rawDescData []byte
)

func file_proto_environment_proto_rawDescGZIP() []byte {
	file_proto_environment_proto_rawDescOnce.Do(func() {
		file_proto_environment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_environment_proto_rawDesc), len(file_proto_environment_proto_rawDesc)))
	})
	return file_proto_environment_proto_rawDescData
}

var file_proto_environment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_environment_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_environment_proto_goTypes = []any{
	(OperationType)(0),              // 0: ryobi.environment.v1.OperationType
	(*RegisterRequest)(nil),         // 1: ryobi.environment.v1.RegisterRequest
	(*EnvironmentConfig)(nil),       // 2: ryobi.environment.v1.EnvironmentConfig
	(*ProviderConfig)(nil),          // 3: ryobi.environment.v1.ProviderConfig
	(*RecipeRegistration)(nil),      // 4: ryobi.environment.v1.RecipeRegistration
	(*EnvironmentCapabilities)(nil), // 5: ryobi.environment.v1.EnvironmentCapabilities
	(*RegisterResponse)(nil),        // 6: ryobi.environment.v1.RegisterResponse
	(*UnregisterRequest)(nil),       // 7: ryobi.environment.v1.UnregisterRequest
	(*UnregisterResponse)(nil),      // 8: ryobi.environment.v1.UnregisterResponse
	(*WatchRequest)(nil),            // 9: ryobi.environment.v1.WatchRequest
	(*ResourceEvent)(nil),           // 10: ryobi.environment.v1.ResourceEvent
	(*ReportResultRequest)(nil),     // 11: ryobi.environment.v1.ReportResultRequest
	(*ReportResultResponse)(nil),    // 12: ryobi.environment.v1.ReportResultResponse
	(*ReportStatusRequest)(nil),     // 13: ryobi.environment.v1.ReportStatusRequest
	(*ResourceHealthStatus)(nil),    // 14: ryobi.environment.v1.ResourceHealthStatus
	(*ReportStatusResponse)(nil),    // 15: ryobi.environment.v1.ReportStatusResponse
	(*HeartbeatRequest)(nil),        // 16: ryobi.environment.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 17: ryobi.environment.v1.HeartbeatResponse
	nil,                             // 18: ryobi.environment.v1.EnvironmentConfig.ProvidersEntry
	nil,                             // 19: ryobi.environment.v1.EnvironmentConfig.TerraformProvidersEntry
	nil,                             // 20: ryobi.environment.v1.RecipeRegistration.DefaultParametersEntry
	nil,                             // 21: ryobi.environment.v1.ResourceEvent.ParametersEntry
	nil,                             // 22: ryobi.environment.v1.ReportResultRequest.OutputsEntry
	nil,                             // 23: ryobi.environment.v1.ResourceHealthStatus.PropertiesEntry
}
var file_proto_environment_proto_depIdxs = []int32{
	2,  // 0: ryobi.environment.v1.RegisterRequest.config:type_name -> ryobi.environment.v1.EnvironmentConfig
	4,  // 1: ryobi.environment.v1.RegisterRequest.recipes:type_name -> ryobi.environment.v1.RecipeRegistration
	5,  // 2: ryobi.environment.v1.RegisterRequest.capabilities:type_name -> ryobi.environment.v1.EnvironmentCapabilities
	18, // 3: ryobi.environment.v1.EnvironmentConfig.providers:type_name -> ryobi.environment.v1.EnvironmentConfig.ProvidersEntry
	19, // 4: ryobi.environment.v1.EnvironmentConfig.terraform_providers:type_name -> ryobi.environment.v1.EnvironmentConfig.TerraformProvidersEntry
	20, // 5: ryobi.environment.v1.RecipeRegistration.default_parameters:type_name -> ryobi.environment.v1.RecipeRegistration.DefaultParametersEntry
	0,  // 6: ryobi.environment.v1.ResourceEvent.operation:type_name -> ryobi.environment.v1.OperationType
	21, // 7: ryobi.environment.v1.ResourceEvent.parameters:type_name -> ryobi.environment.v1.ResourceEvent.ParametersEntry
	22, // 8: ryobi.environment.v1.ReportResultRequest.outputs:type_name -> ryobi.environment.v1.ReportResultRequest.OutputsEntry
	14, // 9: ryobi.environment.v1.ReportStatusRequest.health:type_name -> ryobi.environment.v1.ResourceHealthStatus
	23, // 10: ryobi.environment.v1.ResourceHealthStatus.properties:type_name -> ryobi.environment.v1.ResourceHealthStatus.PropertiesEntry
	3,  // 11: ryobi.environment.v1.EnvironmentConfig.ProvidersEntry.value:type_name -> ryobi.environment.v1.ProviderConfig
	1,  // 12: ryobi.environment.v1.EnvironmentService.Register:input_type -> ryobi.environment.v1.RegisterRequest
	7,  // 13: ryobi.environment.v1.EnvironmentService.Unregister:input_type -> ryobi.environment.v1.UnregisterRequest
	9,  // 14: ryobi.environment.v1.EnvironmentService.WatchResources:input_type -> ryobi.environment.v1.WatchRequest
	11, // 15: ryobi.environment.v1.EnvironmentService.ReportResult:input_type -> ryobi.environment.v1.ReportResultRequest
	13, // 16: ryobi.environment.v1.EnvironmentService.ReportStatus:input_type -> ryobi.environment.v1.ReportStatusRequest
	16, // 17: ryobi.environment.v1.EnvironmentService.Heartbeat:input_type -> ryobi.environment.v1.HeartbeatRequest
	6,  // 18: ryobi.environment.v1.EnvironmentService.Register:output_type -> ryobi.environment.v1.RegisterResponse
	8,  // 19: ryobi.environment.v1.EnvironmentService.Unregister:output_type -> ryobi.environment.v1.UnregisterResponse
	10, // 20: ryobi.environment.v1.EnvironmentService.WatchResources:output_type -> ryobi.environment.v1.ResourceEvent
	12, // 21: ryobi.environment.v1.EnvironmentService.ReportResult:output_type -> ryobi.environment.v1.ReportResultResponse
	15, // 22: ryobi.environment.v1.EnvironmentService.ReportStatus:output_type -> ryobi.environment.v1.ReportStatusResponse
	17, // 23: ryobi.environment.v1.EnvironmentService.Heartbeat:output_type -> ryobi.environment.v1.HeartbeatResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_environment_proto_init() }
func file_proto_environment_proto_init() {
	if File_proto_environment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_environment_proto_rawDesc), len(file_proto_environment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_environment_proto_goTypes,
		DependencyIndexes: file_proto_environment_proto_depIdxs,
		EnumInfos:         file_proto_environment_proto_enumTypes,
		MessageInfos:      file_proto_environment_proto_msgTypes,
	}.Build()
	File_proto_environment_proto = out.File
	file_proto_environment_proto_goTypes = nil
	file_proto_environment_proto_depIdxs = nil
}
