## Ryobi Example: Minimal KubeVirt VM

apiVersion: ryobi/v1
kind: Application
metadata:
  name: simple-vm

resources:
  - name: my-vm
    type: Ryobi.Compute/virtualMachines
    parameters:
      name: my-vm
      memory: 1Gi
      disk_image: "docker://quay.io/containerdisks/fedora:latest"
      disk_size: 10Gi
