apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ryobi-env.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ryobi-env.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ryobi-env.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ryobi-env.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "ryobi-env.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ryobi-env
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - /etc/ryobi/config.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/ryobi
              readOnly: true
            - name: terraform-workdir
              mountPath: {{ .Values.terraform.workDir }}
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "ryobi-env.fullname" . }}
        - name: terraform-workdir
          emptyDir: {}
